#!/usr/bin/env bash

# Select the target directory
if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/Projects ~/.config ~/Documents/GitHub -mindepth 1 -maxdepth 1 -type d | fzf)
fi

# Exit if no directory is selected
if [[ -z $selected ]]; then
    exit 0
fi

# Prepare session name and check if tmux is running
selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

# Function to determine the virtual environment directory
get_venv_dir() {
    if [ -d "$selected/venv" ]; then
        echo "venv"
    elif [ -d "$selected/.venv" ]; then
        echo ".venv"
    else
        echo ""
    fi
}

# Get the virtual environment directory if it exists
VENV_DIR=$(get_venv_dir)

# Case 1: No tmux running and not inside tmux, start a new session with custom setup
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected" -d -n nvim
    tmux new-window -t "$selected_name":2 -c "$selected" -n terminal
    tmux select-window -t "$selected_name":1

    # If a virtual environment exists, activate it
    if [[ -n "$VENV_DIR" ]]; then
        tmux send-keys -t "$selected_name":1 "source $VENV_DIR/bin/activate && clear" C-m
        tmux send-keys -t "$selected_name":2 "source $VENV_DIR/bin/activate && clear" C-m
    fi

    tmux send-keys -t "$selected_name":1 "nvim" C-m
    tmux attach-session -t "$selected_name":1 
    exit 0
fi

# Case 2: Check if the session exists, create it if not
if ! tmux has-session -t="$selected_name" 2> /dev/null; then
    tmux new-session -s "$selected_name" -c "$selected" -d -n nvim
    tmux new-window -t "$selected_name":2 -c "$selected" -n terminal
    tmux select-window -t "$selected_name":1

    # If a virtual environment exists, activate it
    if [[ -n "$VENV_DIR" ]]; then
        tmux send-keys -t "$selected_name":1 "source $VENV_DIR/bin/activate && clear" C-m
        tmux send-keys -t "$selected_name":2 "source $VENV_DIR/bin/activate && clear" C-m
    fi

    tmux send-keys -t "$selected_name":1 "nvim" C-m
fi

# Case 3: Switch to the session if inside tmux, otherwise attach to it
if [[ -n $TMUX ]]; then
    tmux switch-client -t "$selected_name":1
else
    tmux attach-session -t "$selected_name":1
fi
